version: '3.8'

services:
  web:
    build: .
    command: /bin/sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --reload"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: jmart_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}

volumes:
    postgres_data:
