"""create user model

Revision ID: b8afdc8276d4
Revises: 
Create Date: 2024-02-19 03:11:15.502974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8afdc8276d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('t_user_pkey')),
    sa.UniqueConstraint('username', name=op.f('t_user_username_key'))
    )
    op.create_index(op.f('t_user_email_idx'), 't_user', ['email'], unique=True)
    op.create_index(op.f('t_user_id_idx'), 't_user', ['id'], unique=False)
    op.create_index(op.f('t_user_username_idx'), 't_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('t_user_username_idx'), table_name='t_user')
    op.drop_index(op.f('t_user_id_idx'), table_name='t_user')
    op.drop_index(op.f('t_user_email_idx'), table_name='t_user')
    op.drop_table('t_user')
    # ### end Alembic commands ###
